<a href="https://colab.research.google.com/github/Bahrombekk/pytorch/blob/main/Pred_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
from torchvision.io import read_image
from torchvision.models import alexnet,AlexNet_Weights
import torchvision.transforms as T

# Alexnet

ImageNet ma'lumotlar to'plami - bu WordNet ierarxiyasi bo'yicha tashkil etilgan 14 milliondan ortiq izohli tasvirlardan iborat bo'lgan keng ko'lamli vizual aniqlash muammolari ma'lumotlar to'plami.. Ma'lumotlar to'plami 20 000 dan ortiq turli xil ob'ektlar toifalaridagi tasvirlarni o'z ichiga oladi va uning asosiy maqsadi kompyuterni ko'rish va tasvirni aniqlash algoritmlari sohasidagi tadqiqotlar va taqqoslashlarni osonlashtirishdir.

Ma'lumotlar to'plamidagi har bir rasmga u tasvirlangan ob'ekt toifasiga mos keladigan yorliq bilan izohlanadi. Yorliqlar ierarxik va WordNet taksonomiyasiga muvofiq tashkil etilgan, bu tildagi so'zlar o'rtasidagi munosabatlarni belgilaydigan hisoblash leksikasi. WordNet ierarxiyasi ImageNet toifalarini daraxtga o'xshash tuzilishda tashkil qilish uchun ishlatiladi, daraxtdagi har bir tugun boshqa toifaga mos keladi.

ImageNet ma'lumotlar to'plami turli xil kompyuter ko'rish modellarini, shu jumladan AlexNet modeli va boshqa chuqur o'rganish modellarini o'rgatish va baholash uchun keng qo'llaniladi. Bu chuqur o'rganish texnologiyasini rivojlantirishda hal qiluvchi rol o'ynadi va uning kompyuterni ko'rish sohasiga ta'siri juda katta.

In [12]:
weights = AlexNet_Weights.DEFAULT
model = alexnet(weights=weights)
model.eval()

AlexNet(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
  (classifier): Sequential(
    (0): Dropout(p=0.5, inplace=False)
    (1): Linear(in_features=9216, out_features=4096, bias=True)
 

In [13]:
!wget -O cat.jpg "https://daryo.uz/cache/2020/09/photo_2020-09-22_13-51-48-552x414.jpg"

--2023-07-14 16:07:51--  https://daryo.uz/cache/2020/09/photo_2020-09-22_13-51-48-552x414.jpg
Resolving daryo.uz (daryo.uz)... 82.196.13.41
Connecting to daryo.uz (daryo.uz)|82.196.13.41|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 32735 (32K) [image/jpeg]
Saving to: ‘cat.jpg’

cat.jpg             100%[===================>]  31.97K  --.-KB/s    in 0s      

2023-07-14 16:07:52 (119 MB/s) - ‘cat.jpg’ saved [32735/32735]



In [14]:
img=read_image("cat.jpg")

In [15]:
img.shape

torch.Size([3, 414, 552])

In [16]:
preprocess=weights.transforms()
pred=preprocess(img).unsqueeze(0)

In [17]:
pred.shape

torch.Size([1, 3, 224, 224])

In [18]:
r=model(pred)
r.argmax(axis=1)

tensor([281])

In [19]:
(weights.meta["categories"][281])

'tabby'

#ConvNeXt

ImageNet ma'lumotlar to'plami - bu WordNet ierarxiyasi bo'yicha tashkil etilgan 14 milliondan ortiq izohli tasvirlardan iborat bo'lgan keng ko'lamli vizual aniqlash muammolari ma'lumotlar to'plami.. Ma'lumotlar to'plami 20 000 dan ortiq turli xil ob'ektlar toifalaridagi tasvirlarni o'z ichiga oladi va uning asosiy maqsadi kompyuterni ko'rish va tasvirni aniqlash algoritmlari sohasidagi tadqiqotlar va taqqoslashlarni osonlashtirishdir.

Ma'lumotlar to'plamidagi har bir rasmga u tasvirlangan ob'ekt toifasiga mos keladigan yorliq bilan izohlanadi. Yorliqlar ierarxik va WordNet taksonomiyasiga muvofiq tashkil etilgan, bu tildagi so'zlar o'rtasidagi munosabatlarni belgilaydigan hisoblash leksikasi. WordNet ierarxiyasi ImageNet toifalarini daraxtga o'xshash tuzilishda tashkil qilish uchun ishlatiladi, daraxtdagi har bir tugun boshqa toifaga mos keladi.

ImageNet ma'lumotlar to'plami turli xil kompyuter ko'rish modellarini, shu jumladan AlexNet modeli va boshqa chuqur o'rganish modellarini o'rgatish va baholash uchun keng qo'llaniladi. Bu chuqur o'rganish texnologiyasini rivojlantirishda hal qiluvchi rol o'ynadi va uning kompyuterni ko'rish sohasiga ta'siri juda katta.

In [ ]:
from torchvision.models import convnext_large,ConvNeXt_Large_Weights

In [ ]:
weights=ConvNeXt_Large_Weights.DEFAULT
model=convnext_large(weights=weights)
model.eval()

ConvNeXt(
  (features): Sequential(
    (0): Conv2dNormActivation(
      (0): Conv2d(3, 192, kernel_size=(4, 4), stride=(4, 4))
      (1): LayerNorm2d((192,), eps=1e-06, elementwise_affine=True)
    )
    (1): Sequential(
      (0): CNBlock(
        (block): Sequential(
          (0): Conv2d(192, 192, kernel_size=(7, 7), stride=(1, 1), padding=(3, 3), groups=192)
          (1): Permute()
          (2): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (3): Linear(in_features=192, out_features=768, bias=True)
          (4): GELU(approximate='none')
          (5): Linear(in_features=768, out_features=192, bias=True)
          (6): Permute()
        )
        (stochastic_depth): StochasticDepth(p=0.0, mode=row)
      )
      (1): CNBlock(
        (block): Sequential(
          (0): Conv2d(192, 192, kernel_size=(7, 7), stride=(1, 1), padding=(3, 3), groups=192)
          (1): Permute()
          (2): LayerNorm((192,), eps=1e-06, elementwise_affine=True)
          (3): Linear(

In [ ]:
!wget -O dog.jpg "https://hips.hearstapps.com/hmg-prod/images/golden-retriever-royalty-free-image-506756303-1560962726.jpg?crop=1.00xw:0.756xh;0,0.0756xh&resize=1200:*"

--2023-07-14 15:54:23--  https://hips.hearstapps.com/hmg-prod/images/golden-retriever-royalty-free-image-506756303-1560962726.jpg?crop=1.00xw:0.756xh;0,0.0756xh&resize=1200:*
Resolving hips.hearstapps.com (hips.hearstapps.com)... 151.101.0.155, 151.101.64.155, 151.101.128.155, ...
Connecting to hips.hearstapps.com (hips.hearstapps.com)|151.101.0.155|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 133809 (131K) [image/jpeg]
Saving to: ‘dog.jpg’

dog.jpg             100%[===================>] 130.67K  --.-KB/s    in 0.01s   

2023-07-14 15:54:23 (8.94 MB/s) - ‘dog.jpg’ saved [133809/133809]



In [ ]:
img1=read_image("dog.jpg")
img1.shape

torch.Size([3, 605, 1200])

In [ ]:
preprocess=weights.transforms()
pred=preprocess(img1).unsqueeze(0)
pred.shape

torch.Size([1, 3, 224, 224])

In [ ]:
a=model(pred)
a.argmax(axis=1)

tensor([207])

In [ ]:
weights.meta["categories"][207]

'golden retriever'

#DenseNet
densenet201

In [ ]:
from torchvision.models import densenet201,DenseNet201_Weights

In [ ]:
weights=DenseNet201_Weights.DEFAULT
model=densenet201(weights=weights)
model.eval()

DenseNet(
  (features): Sequential(
    (conv0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (norm0): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu0): ReLU(inplace=True)
    (pool0): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (denseblock1): _DenseBlock(
      (denselayer1): _DenseLayer(
        (norm1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu1): ReLU(inplace=True)
        (conv1): Conv2d(64, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (norm2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu2): ReLU(inplace=True)
        (conv2): Conv2d(128, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      )
      (denselayer2): _DenseLayer(
        (norm1): BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu

In [ ]:
!wget -O fil.jpg "https://bilimgenc.tubitak.gov.tr/sites/default/files/styles/bp-770px-custom_user_desktop_1x/public/haber_fil_os_msson_451244723_smal56l.jpg?itok=4OAr12MW"

--2023-07-14 15:54:25--  https://bilimgenc.tubitak.gov.tr/sites/default/files/styles/bp-770px-custom_user_desktop_1x/public/haber_fil_os_msson_451244723_smal56l.jpg?itok=4OAr12MW
Resolving bilimgenc.tubitak.gov.tr (bilimgenc.tubitak.gov.tr)... 193.140.80.51
Connecting to bilimgenc.tubitak.gov.tr (bilimgenc.tubitak.gov.tr)|193.140.80.51|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 51256 (50K) [image/jpeg]
Saving to: ‘fil.jpg’

fil.jpg             100%[===================>]  50.05K   244KB/s    in 0.2s    

2023-07-14 15:54:27 (244 KB/s) - ‘fil.jpg’ saved [51256/51256]



In [ ]:
img2=read_image("fil.jpg")
img2.shape

torch.Size([3, 718, 870])

In [ ]:
preprocess=weights.transforms()
pred=preprocess(img2).unsqueeze(0)
pred.shape

torch.Size([1, 3, 224, 224])

In [ ]:
b=model(pred)
b.argmax(axis=1)

tensor([386])

In [ ]:
weights.meta['categories'][386]

'African elephant'

# EfficientNet

CIFAR-100 dataset tizimida turli xil obyektlarning tasvirlari mavjud. Ushbu dataset 32x32 piksel o'lchamdagi 60,000 ta rangli tasvirlarni o'z ichiga oladi, 100 ta turdagi obyektlar to'plamidan. Har bir obyekt turiga 600 ta tasvir tushirilgan. Shu sababli, bu dataset katta miqdorda Tasvirlarni aniq yoki sinflandirish vazifalarini bajarish uchun ishlatiladi.

 Xususan, bizning EfficientNet-B7 eng yaxshi mavjud ConvNet-ga qaraganda 8,4 baravar kichikroq va 6,1 baravar tezroq xulosa chiqarish bilan birga, ImageNet-da 84,3 foiz yuqori darajadagi eng zamonaviy aniqlikka erishadi. Bizning EfficientNets ham yaxshi uzatadi va CIFAR-100 (91,7%), Gullar (98,8%) va boshqa 3 ta uzatish o'rganish ma'lumotlar to'plamida eng so'nggi aniqlikka erishadi, parametrlari kamroq.

In [ ]:
from torchvision.models import efficientnet_b7,EfficientNet_B7_Weights

In [ ]:
weights=EfficientNet_B7_Weights.DEFAULT
model=efficientnet_b7(weights=weights)
model.eval()

EfficientNet(
  (features): Sequential(
    (0): Conv2dNormActivation(
      (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (1): BatchNorm2d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      (2): SiLU(inplace=True)
    )
    (1): Sequential(
      (0): MBConv(
        (block): Sequential(
          (0): Conv2dNormActivation(
            (0): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=64, bias=False)
            (1): BatchNorm2d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
            (2): SiLU(inplace=True)
          )
          (1): SqueezeExcitation(
            (avgpool): AdaptiveAvgPool2d(output_size=1)
            (fc1): Conv2d(64, 16, kernel_size=(1, 1), stride=(1, 1))
            (fc2): Conv2d(16, 64, kernel_size=(1, 1), stride=(1, 1))
            (activation): SiLU(inplace=True)
            (scale_activation): Sigmoid()
          )
          (2): Conv2dNormAct

In [ ]:
preprocess=weights.transforms()
pred=preprocess(img2).unsqueeze(0)

In [ ]:
c=model(pred)
c.argmax(axis=1)

tensor([386])

In [ ]:
weights.meta['categories'][386]

'African elephant'

# VGG

In [ ]:
from torchvision.models import vgg19_bn,VGG19_BN_Weights

In [ ]:
weights=VGG19_BN_Weights.DEFAULT
model=vgg19_bn(weights=weights)
model.eval()

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU(inplace=True)
    (6): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (7): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (9): ReLU(inplace=True)
    (10): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (12): ReLU(inplace=True)
    (13): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (14): Conv2d(128, 256

In [ ]:
preprocess=weights.transforms()
pred=preprocess(img).unsqueeze(0)

In [ ]:
d=model(pred)
d.argmax(axis=1)

tensor([281])

In [ ]:
weights.meta['categories'][281]

'tabby'

# ResNeXt

In [ ]:
from torchvision.models import resnext101_64x4d,ResNeXt101_64X4D_Weights

In [ ]:
weights=ResNeXt101_64X4D_Weights.DEFAULT
model=resnext101_64x4d(weights=weights)
model.eval()

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=64, bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1

In [ ]:
preprocess=weights.transforms()
pred=preprocess(img).unsqueeze(0)

In [ ]:
g=model(pred)
g.argmax()

tensor(281)

In [ ]:
weights.meta['categories'][281]

'tabby'

# GoogLeNet

In [ ]:
from torchvision.models import googlenet,GoogLeNet_Weights

In [ ]:
weights=GoogLeNet_Weights.DEFAULT
model=googlenet(weights=weights)
model.eval()

GoogLeNet(
  (conv1): BasicConv2d(
    (conv): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn): BatchNorm2d(64, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
  )
  (maxpool1): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=True)
  (conv2): BasicConv2d(
    (conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (bn): BatchNorm2d(64, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
  )
  (conv3): BasicConv2d(
    (conv): Conv2d(64, 192, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn): BatchNorm2d(192, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
  )
  (maxpool2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=True)
  (inception3a): Inception(
    (branch1): BasicConv2d(
      (conv): Conv2d(192, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(64, eps=0.001, momentum=0.1, affine=True, track

In [ ]:
preprocess=weights.transforms()
pred=preprocess(img).unsqueeze(0)

In [ ]:
h=model(pred)
h.argmax(axis=1)

tensor([281])

In [ ]:
weights.meta['categories'][281]

'tabby'

# VisionTransformer

In [20]:
from torchvision.models import vit_h_14,ViT_H_14_Weights

In [21]:
weights=ViT_H_14_Weights.DEFAULT
model=vit_h_14(weights=weights)
model.eval()

VisionTransformer(
  (conv_proj): Conv2d(3, 1280, kernel_size=(14, 14), stride=(14, 14))
  (encoder): Encoder(
    (dropout): Dropout(p=0.0, inplace=False)
    (layers): Sequential(
      (encoder_layer_0): EncoderBlock(
        (ln_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (self_attention): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=1280, out_features=1280, bias=True)
        )
        (dropout): Dropout(p=0.0, inplace=False)
        (ln_2): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
        (mlp): MLPBlock(
          (0): Linear(in_features=1280, out_features=5120, bias=True)
          (1): GELU(approximate='none')
          (2): Dropout(p=0.0, inplace=False)
          (3): Linear(in_features=5120, out_features=1280, bias=True)
          (4): Dropout(p=0.0, inplace=False)
        )
      )
      (encoder_layer_1): EncoderBlock(
        (ln_1): LayerNorm((1280,), eps=1e-06, elementwise_affine=True)
       

In [22]:
preprocess=weights.transforms()
pred=preprocess(img).unsqueeze(0)

In [ ]:
w=model(pred)
w.argmax(axis=1)