<a href="https://colab.research.google.com/github/Bahrombekk/pytorch/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22PyTorch_Homework_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

### Create array

# Numerical Python

In [2]:
def list_arr(list1):
  '''
  Convert list the array
  '''

  return torch.tensor(list1)

In [3]:
list_arr([1,2,3,4])

tensor([1, 2, 3, 4])

In [17]:
def even_array(lst):
  '''
  Convert only even items to array
  '''
  # CODE
  l=[]
  for i in lst:
    if i%2==0:
      l.append(i)
  return torch.tensor(l)

In [18]:
even_array([1,2,3,4,5,6,7,8])

tensor([2, 4, 6, 8])

## PyTorch Tensor properties


In [19]:
def arry_1D():
  '''
  Create any 1D array 
  '''
  lst = [0,1,2,3,4]
  # CODE
  return torch.tensor(lst)

In [20]:
arry_1D()

tensor([0, 1, 2, 3, 4])

In [21]:
def arry_2D():
  '''
  Create any 2D array 
  '''
  lst=[[1,2,3],
       [4,5,6]]
  # CODE
  return torch.tensor(lst)

In [22]:
arry_2D()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
def arry_3D():
  '''
  Create any 3D array 
  '''
  # CODE
  lst=[[[1,2,3]]]
  return torch.tensor(lst)

In [26]:
arry_3D().ndim

3

### The shape of the array
 **size**  - Return size of tensor.					
 **Returns**: tensor



In [33]:
def arry_3x3():
  '''
  Create any 3x3 array 
  '''
  # CODE
  lst=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
  return torch.tensor(lst)

In [34]:
arry_3x3().size()

torch.Size([3, 3])

In [37]:
def arry_2x3():
  '''
  Create lst to 2x3 array 
  return 1D
  '''
  # CODE
  lst=[[1,2,3],[3,4,5]]
  return torch.tensor(lst)

In [38]:
arry_2x3().size()

torch.Size([2, 3])

# Creating Arrays

### torch.arange

In [39]:
def arange_1D_arr():
  '''
  Create any 1D array
  return array
  '''
  # CODE
  return torch.arange(10) 

In [40]:
arange_1D_arr()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
def arrange_array(n):
  '''
  Create any array from 0 to n
  return array
  '''
  # CODE
  return torch.arange(n)

In [42]:
arrange_array(5)

tensor([0, 1, 2, 3, 4])

### torch.linspace

In [51]:
def linspace_arr(n):
  '''
  Create an array of the range 0 and n divided by 10
  return array
  '''
  # CODE
  return torch.linspace(0,n,10)

In [52]:
linspace_arr(12)

tensor([ 0.0000,  1.3333,  2.6667,  4.0000,  5.3333,  6.6667,  8.0000,  9.3333,
        10.6667, 12.0000])

### torch.zeros

In [53]:
def array_zeros_nxm(n,m):
  '''
  Create an nxm array of zeros
  return array
  '''
  # CODE
  return torch.zeros((n,m))

In [54]:
array_zeros_nxm(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [55]:
def array_zeros_3D(n, m, ch):
  '''
  Create any an 3D array of zeros
  return 3D array
  ''' 
  # CODE
  return torch.zeros((n,m,ch))

In [56]:
array_zeros_3D(5, 5, 3)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

### torch.ones

In [57]:
def array_zeros_nxm(n,m):
  '''
  Create an nxm array of ones
  return array
  '''
  # CODE
  return torch.ones((n,m))

In [58]:
array_zeros_nxm(4, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

### torch.full

In [61]:
def array_full_3D(n,m,k):
  '''
  Create any an 3D array of seven, shape = (n,m,k)
  return 3D array
  ''' 
  # CODE
  return torch.full((n,m),k)

In [62]:
array_full_3D(3, 4, 255)

tensor([[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]])